# ...
localConfigTemplatesPath: /templates # this must match with yoyur templates path

# with the provided templates we can easily include them directly in the config
sonarr:
  instance1:
    # ...

    include:
      # ...
      #### Custom
      - template: sonarr-german-new-cfs
      - template: sonarr-german-new-cfs-quality
      - template: sonarr-german-cfs
      - template: sonarr-german-qps
